# Generated by Django 6.0 on 2025-12-30 02:10

import core.models.media
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name.', max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly tag name.', unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('editor', 'Editor'), ('author', 'Author'), ('subscriber', 'Subscriber')], default='subscriber', help_text='User role determines their permissions in the system.', max_length=20, verbose_name='role')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled for this user.', verbose_name='two-factor authentication enabled')),
                ('two_factor_secret', models.CharField(blank=True, help_text='Secret key for two-factor authentication.', max_length=32, null=True, verbose_name='two-factor secret')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Number of consecutive failed login attempts.', verbose_name='failed login attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Timestamp of the last failed login attempt.', null=True, verbose_name='last failed login')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='If set, the account is locked until this timestamp.', null=True, verbose_name='account locked until')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description of the user.', verbose_name='bio')),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image.', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name.', max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly category name.', max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Category description.', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload a file (images, videos, documents).', upload_to=core.models.media.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'webm', 'ogg', 'mp3', 'wav', 'ogg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt'])], verbose_name='file')),
                ('title', models.CharField(help_text='Descriptive title for the media file.', max_length=200, verbose_name='title')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (important for images).', max_length=200, verbose_name='alt text')),
                ('caption', models.TextField(blank=True, help_text='Caption or description for the media file.', verbose_name='caption')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], help_text='Type of media file.', max_length=20, verbose_name='file type')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file.', max_length=100, verbose_name='MIME type')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.', verbose_name='file size')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels.', null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels.', null=True, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title (max 200 characters).', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL-friendly version of the title.', max_length=200, unique=True, verbose_name='slug')),
                ('content', models.TextField(help_text='Page content (supports rich text/HTML).', verbose_name='content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the page.', max_length=20, verbose_name='status')),
                ('template', models.CharField(choices=[('default', 'Default Template'), ('fullwidth', 'Full Width'), ('landing', 'Landing Page'), ('contact', 'Contact Page')], default='default', help_text='Template to use for rendering this page.', max_length=50, verbose_name='template')),
                ('menu_order', models.IntegerField(default=0, help_text='Order in navigation menus (lower numbers appear first).', verbose_name='menu order')),
                ('show_in_menu', models.BooleanField(default=True, help_text='Whether to show this page in navigation menus.', verbose_name='show in menu')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters).', max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated).', max_length=255, verbose_name='meta keywords')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when the page was published.', null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(help_text='Author of the page.', on_delete=django.db.models.deletion.PROTECT, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Main image for the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_pages', to='core.media', verbose_name='featured image')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent page for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.page', verbose_name='parent page')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title (max 200 characters).', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL-friendly version of the title.', max_length=200, unique=True, verbose_name='slug')),
                ('content', models.TextField(help_text='Post content (supports rich text/HTML).', verbose_name='content')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt or summary of the post.', verbose_name='excerpt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', help_text='Publication status of the post.', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when the post was/will be published.', null=True, verbose_name='published at')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters).', max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated).', max_length=255, verbose_name='meta keywords')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed.', verbose_name='view count')),
                ('allow_comments', models.BooleanField(default=True, help_text='Whether comments are allowed on this post.', verbose_name='allow comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(help_text='Author of the post.', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this post belongs to.', related_name='posts', to='core.category', verbose_name='categories')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Main image for the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_posts', to='core.media', verbose_name='featured image')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for this post.', related_name='posts', to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_type'], name='core_media_file_ty_34b51e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='core_media_uploade_f4643a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='core_page_slug_904ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'published_at'], name='core_page_status_81eeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['menu_order'], name='core_page_menu_or_d316a7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='core_post_slug_474b18_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='core_post_status_ec2809_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status'], name='core_post_author__e7ef55_idx'),
        ),
    ]
